version: '3'
services:
  dbpostgres:
    build: ./dbpostgres
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
  dbmongo:
    image: mongo:4-xenial
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./localidades.json:/data/localidades.json
  api:
    build: ./api
    volumes:
      - ./api:/app/
    ports:
      - 3000:3000
    environment:
      RACK_ENV: production
      RAILS_ENV: production
    depends_on:
      - dbpostgres
      - dbmongo
